"""add column address_user

Revision ID: ce816f00cc88
Revises: 20260517_01
Create Date: 2026-05-17 13:57:26.640060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ce816f00cc88'
down_revision: Union[str, None] = '20260517_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('craw_data')
    op.alter_column('crawl_data', 'price',
               existing_type=mysql.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('crawl_data', 'area',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('crawl_data', 'latitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crawl_data', 'longitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crawl_data', 'longitude',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('crawl_data', 'latitude',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('crawl_data', 'area',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('crawl_data', 'price',
               existing_type=mysql.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.create_table('craw_data',
    sa.Column('url', mysql.VARCHAR(length=767), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.Column('price', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('area', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0'"), nullable=True),
    sa.Column('room_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('amenities', mysql.TEXT(), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('images', mysql.TEXT(), nullable=True),
    sa.Column('posted_date', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('url'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
